
DROP TABLE AUTORI CASCADE CONSTRAINTS;
DROP TABLE EDITURI CASCADE CONSTRAINTS;
DROP TABLE RAFTURI CASCADE CONSTRAINTS;
DROP TABLE ZONE CASCADE CONSTRAINTS;
DROP TABLE CARTI CASCADE CONSTRAINTS;
DROP TABLE CLIENTI CASCADE CONSTRAINTS;
DROP TABLE VANZARI CASCADE CONSTRAINTS;
DROP TABLE RAND_VANZARE CASCADE CONSTRAINTS;

CREATE TABLE AUTORI (
ID_AUTOR NUMBER(5), 
NUME VARCHAR(50) NOT NULL,
PRENUME VARCHAR(50),
NATIONALITATE VARCHAR(50),
CONSTRAINT AUTORI_PK PRIMARY KEY(ID_AUTOR)
);
DESC AUTORI;

CREATE TABLE EDITURI(
ID_EDITURA NUMBER(5),
NUME VARCHAR(50) NOT NULL,
DATA_ULTIMA_ACHIZITIE DATE, 
CONSTRAINT EDITURI_PK PRIMARY KEY(ID_EDITURA)
);
DESC EDITURI;

CREATE TABLE ZONE (
ID_ZONA NUMBER(5),
NUME_ZONA VARCHAR(50) NOT NULL,
NR_ANGAJATI NUMBER(3) DEFAULT 1,
SUPRAFATA_MP NUMBER(10,2),
ID_ZONA_PARINTE NUMBER(5),
CONSTRAINT ZONE_PK PRIMARY KEY (ID_ZONA),
CONSTRAINT ZONE_SELF_FK FOREIGN KEY (ID_ZONA_PARINTE) REFERENCES ZONE(ID_ZONA)
);
DESC ZONE;

CREATE TABLE RAFTURI(
ID_RAFT NUMBER(5),
ID_ZONA NUMBER(5),
TAXA_PER_CARTE NUMBER(7,2) DEFAULT 10,
CAPACITATE_MAXIMA NUMBER(5),
CONSTRAINT RAFTURI_PK PRIMARY KEY(ID_RAFT),
CONSTRAINT RAFT_ZONA_FK FOREIGN KEY (ID_ZONA) REFERENCES ZONE(ID_ZONA)
);
DESC RAFTURI;

CREATE TABLE CARTI(
ID_CARTE NUMBER(5),
TITLU VARCHAR(50) NOT NULL,
ID_AUTOR NUMBER(5) NOT NULL,
ID_EDITURA NUMBER(5) NOT NULL,
ID_RAFT NUMBER(5),
PRET_ACHIZITIE NUMBER(7,2) NOT NULL,
STOC NUMBER(10),
CONSTRAINT CARTI_PK PRIMARY KEY(ID_CARTE),
CONSTRAINT CARTI_AUTOR_FK FOREIGN KEY(ID_AUTOR) REFERENCES AUTORI,
CONSTRAINT CARTE_EDITURA_FK FOREIGN KEY(ID_EDITURA) REFERENCES EDITURI,
CONSTRAINT CARTE_RAFT_FK FOREIGN KEY(ID_RAFT)REFERENCES RAFTURI
);
DESC CARTI;

CREATE TABLE CLIENTI (
ID_CLIENT NUMBER(5),
NUME VARCHAR(50)NOT NULL,
PRENUME VARCHAR(50),
NR_TELEFON VARCHAR(15),
CONSTRAINT CLIENTI_PK PRIMARY KEY(ID_CLIENT)
);
DESC CLIENTI;

CREATE TABLE VANZARI (
ID_VANZARE NUMBER(5),
ID_CLIENT NUMBER(5) NOT NULL,
CONSTRAINT VANZARI_PK PRIMARY KEY(ID_VANZARE),
CONSTRAINT VANZARI_CLIENTI_FK FOREIGN KEY(ID_CLIENT) REFERENCES CLIENTI
);
ALTER TABLE VANZARI ADD DATA_VANZARE DATE;
DESC VANZARI;

CREATE TABLE RAND_VANZARE (
ID_RAND NUMBER(5),
ID_VANZARE NUMBER(5) NOT NULL,
ID_CARTE NUMBER(5)NOT NULL,
CANTITATE NUMBER(10) NOT NULL,
PRET NUMBER(7,2)NOT NULL,
CONSTRAINT RAND_VANZARI_PK PRIMARY KEY (ID_RAND),
CONSTRAINT RAND_VANZARE_FK FOREIGN KEY (ID_VANZARE) REFERENCES VANZARI,
CONSTRAINT RAND_VANZARE_CARTI_FK FOREIGN KEY (ID_CARTE) REFERENCES CARTI 
);
ALTER TABLE RAND_VANZARE ADD CONSTRAINT RAND_VANZARE_CH_PRET CHECK (PRET >=10);
DESC RAND_VANZARE;

