--Exemple de interogări cât mai variate și relevante pentru tema aleasă (min 15) 

--1.SA SE AFISEZE CARTILE CARE AU UN PRET DE ACHIZITIE MAI MARE DE 50
SELECT TITLU, PRET_ACHIZITIE FROM CARTI WHERE PRET_ACHIZITIE > 50;

--2.SA SE AFISEZE TOTI AUTORII CARE NU SUNT DE NATIONALITATE ROMANA
SELECT NUME, NATIONALITATE FROM AUTORI WHERE NATIONALITATE != 'Romana';

--3.SA SE AFISEZE CLIENTII CARE NU AU PRENUMELE SALVAT IN BAZA DE DATE
SELECT NUME, PRENUME FROM CLIENTI WHERE PRENUME IS NULL;

--4.SA SE AFISEZE TOTI AUTORII AL CAROR NUME INCEPE CU LITERA E
SELECT NUME, PRENUME FROM AUTORI WHERE NUME LIKE 'E%';

--5.SA SE AFISEZE CARTILE CARE CONTIN CUVANTUL "Noapte" ORIUNDE IN TITLU
SELECT TITLU FROM CARTI WHERE TITLU LIKE '%Noapte%';

--6.SA SE AFISEZE CLIENTII CARE AU UN NUME CEINCEOE CU  P SI AU ID-UL MAI MARE DE 2000
SELECT * FROM CLIENTI WHERE NUME LIKE 'P%' AND ID_CLIENT > 2000;

--7.SA SE AFISEZE RAFTURILE CARE SE AFLA LA ETAJ 
SELECT * FROM RAFTURI WHERE ID_ZONA IN (300, 310);

--8.SA SE AFISEZE NUMELE CLIENTILOR SI ULTIMELE 4 CIFRE DIN NR DE TELEFON
SELECT NUME, PRENUME, SUBSTR(NR_TELEFON, 6, 4) AS ULTIMELE_CIFRE FROM CLIENTI;

--9. sA SE AFISEZE O LISTA CU TOTI CLIENTII. DACA UN CLIENT NU ARE NUMELE INTRODUS SA SE AFISEZE "ANONIM"
SELECT NUME, NVL(PRENUME, 'ANONIM') AS PRENUME, NR_TELEFON FROM CLIENTI;

--10.SA SE AFISEZE TOATE VANZARILE EFECTUATE INTRE 1 IANUARIE 2025 SI 1 IANUARIE 2026
SELECT ID_VANZARE, ID_CLIENT, DATA_VANZARE FROM VANZARI
WHERE DATA_VANZARE BETWEEN TO_DATE('01-01-2025', 'DD-MM-YYYY') AND TO_DATE('01-01-2026', 'DD-MM-YYYY');

--11.SA SE AFISEZE TITLUL CARTILOR SI O DESCRIERE A PRETULUI FOLOSIND CASE 
SELECT TITLU, PRET_ACHIZITIE,
 CASE 
    WHEN PRET_ACHIZITIE < 30 THEN 'IEFTINA'
    WHEN PRET_ACHIZITIE BETWEEN 30 AND 50 THEN 'MEDIE'
    ELSE 'SCUMPA'
    END AS CATEGORIE_PRET
FROM CARTI;

--12.SA SE EXTRAGA LUNA SI ZIUA DIN DATA VANZARILOR EFECTUATE IN ANUL 2026
SELECT ID_VANZARE, 
    TO_CHAR(DATA_VANZARE, 'DD-Mon-YYYY') AS DATA_FORMATA,
    EXTRACT(DAY FROM DATA_VANZARE) AS ZIUA_VANZARII,
    EXTRACT(MONTH FROM DATA_VANZARE) AS LUNA_VANZARII
FROM VANZARI WHERE DATA_VANZARE >= TO_DATE('01-01-2026', 'DD-MM-YYYY');

--13.sA SE AFISEZE DETALIILE CARTILOR CARE AU PRETUL DE ACHIZITIE MAI MARE DECAT PRETUL MEDIU AL TUTUROR CARTILOR 
SELECT TITLU, PRET_ACHIZITIE 
FROM CARTI 
WHERE PRET_ACHIZITIE > (SELECT AVG(PRET_ACHIZITIE) FROM CARTI);

--14. sA SE AFISEZE ID-UL SI NUMELE AUTORILOR CARE AU CARTI LA HUMANITAS DAR NU AU NICIO CARTE PUBLICATA LA POLIROM
SELECT A.ID_AUTOR, A.NUME FROM AUTORI A
JOIN CARTI C ON A.ID_AUTOR = C.ID_AUTOR
WHERE C.ID_EDITURA = 1
MINUS
SELECT A.ID_AUTOR, A.NUME FROM AUTORI A
JOIN CARTI C ON A.ID_AUTOR = C.ID_AUTOR
WHERE C.ID_EDITURA = 2;

--15.SA SE OBTINA O LISTA CU ID-URILE CLIENTILOR CARE AU CUMPARAT IN LUNA IANUARIE SI A CELOR CARE AU CUMPARAT IN LUNA MAI
SELECT ID_CLIENT FROM VANZARI WHERE TO_CHAR(DATA_VANZARE, 'MM') = '01'
UNION
SELECT ID_CLIENT FROM VANZARI WHERE TO_CHAR(DATA_VANZARE, 'MM') = '05';

--16.SA SE AFISEZE ID-UL SI NUMELE AUTORILOR CARE AU CARTI PUBLICATE ATAT LA EDITURA 1 CAT SI LA EDITURA 2
SELECT A.ID_AUTOR, A.NUME FROM AUTORI A
JOIN CARTI C ON A.ID_AUTOR = C.ID_AUTOR WHERE C.ID_EDITURA = 1
INTERSECT
SELECT A.ID_AUTOR, A.NUME FROM AUTORI A
JOIN CARTI C ON A.ID_AUTOR = C.ID_AUTOR WHERE C.ID_EDITURA = 2;

--17.SA SE CALCULEZE VALOAREA TOTALA A VANZARILOR PENTRU FIECARE CLIENT. SE VOR AFISA DOAR CLIENTII CARE AU CHELTUIT MAI MULT DE 200
SELECT C.NUME, SUM(RV.CANTITATE * RV.PRET) AS TOTAL_CHELTUIT
FROM CLIENTI C
JOIN VANZARI V ON C.ID_CLIENT = V.ID_CLIENT
JOIN RAND_VANZARE RV ON V.ID_VANZARE = RV.ID_VANZARE
GROUP BY C.NUME
HAVING SUM(RV.CANTITATE * RV.PRET) > 200;

--SA SE CALCULEZE CAT ARE DE PLATIT FIECARE EDITURA IN FUNCTIE DE RAFTUL PE CARE AU DECIS SA ISI EXPUNA CARTILE
SELECT E.NUME AS EDITURA,SUM(C.STOC) AS TOTAL_CARTI_STOC,SUM(C.STOC * R.TAXA_PER_CARTE) AS TOTAL_DE_PLATIT
FROM EDITURI E JOIN CARTI C ON E.ID_EDITURA = C.ID_EDITURA
JOIN RAFTURI R ON C.ID_RAFT = R.ID_RAFT
GROUP BY E.NUME ORDER BY TOTAL_DE_PLATIT DESC;

--18.SA SE CREEZE O SECVENTA PENTRU GENERAREA AUTOMATA A ID-URILOR DE VANZARI 
DROP SEQUENCE SEQ_ID_VANZARE;
CREATE SEQUENCE SEQ_ID_VANZARE START WITH 100 INCREMENT BY 1;
INSERT INTO VANZARI VALUES (SEQ_ID_VANZARE.NEXTVAL, 1254, SYSDATE);
INSERT INTO VANZARI VALUES (SEQ_ID_VANZARE.NEXTVAL, 1254, SYSDATE);
INSERT INTO VANZARI VALUES (SEQ_ID_VANZARE.NEXTVAL, 1254, SYSDATE);
SELECT * FROM VANZARI;

--19.SA SE CREEZE UN INDEX PENTRU OPTIMIZAREA CAUTARII CARTILOR DUPA TITLU 
DROP INDEX IDX_TITLU_CARTE;
CREATE INDEX IDX_TITLU_CARTE ON CARTI(TITLU);

--20.SA SE AFISEZE TOTI AUTORII SI TITLURILE CARTILOR LOR, INCLUSIV AUTORII CARE NU AU NICIO CARTE INREGISTRATA 
SELECT A.NUME, C.TITLU FROM AUTORI A LEFT OUTER JOIN CARTI C ON A.ID_AUTOR = C.ID_AUTOR;

--21.SA SE AFISEZE TITLUL CARTILOR , PRETUL DE ACHIZITIE SI O COLOANA "REDUCERE". CARTILE EDITURII 1 AU 10% REDUCERE, CELE DE LA EDITURA 2 AU 20% SI RESTUL 0%,DOAR DACA NR DE CARTI DIN STOC ESTE INTRE 10 SI 50.
SELECT TITLU, PRET_ACHIZITIE, DECODE(ID_EDITURA, 1, PRET_ACHIZITIE*0.1, 2, PRET_ACHIZITIE*0.2, 0) AS REDUCERE
FROM CARTI WHERE STOC BETWEEN 10 AND 50;

--22. SA SE AFISEZE TITLUL SI PRETUL CARTILOR CARE SUNT CELE MAI SCUMPE DE PE RAFTUL LOR.
SELECT C1.TITLU, C1.PRET_ACHIZITIE, C1.ID_RAFT FROM CARTI C1
WHERE C1.PRET_ACHIZITIE = (SELECT MAX(C2.PRET_ACHIZITIE) FROM CARTI C2 
WHERE C2.ID_RAFT = C1.ID_RAFT);

--23.SA SE AFISEZE STRUCTURA IERARHICA A ZONELOR DIN LIBRARIE,INDICAND NIVELUL FIECAREI LOCATII SI CALEA COMPLETA DE ACCES DE LA CLADIRE PANA LA ZONA RESPECTIVA 
SELECT LEVEL AS NIVEL,NUME_ZONA AS STRUCTURA_CLADIRE,NR_ANGAJATI, SYS_CONNECT_BY_PATH(NUME_ZONA, ' > ') AS CALE_ACCES
FROM ZONE START WITH ID_ZONA_PARINTE IS NULL CONNECT BY PRIOR ID_ZONA = ID_ZONA_PARINTE;

--24.SA SE CREEZE O TABELA VIRTUALA CARE SA CALCULEZE PENTRU FIECARE EDITURA NUMARUL TOTAL DE TITLURI DETINUTE, VALOAREA TOTALA A INVENTARULUI(STOC * PRET ACHIZITIE) SI PRETUL MEDIU AL CARTILOR
CREATE OR REPLACE VIEW VW_EDITURI AS
SELECT E.NUME AS EDITURA,COUNT(C.ID_CARTE) AS NUMAR_TITLURI, SUM(C.STOC) AS TOTAL_STOC,
SUM(C.STOC * C.PRET_ACHIZITIE) AS VALOARE_INVENTAR_ACHIZITIE, ROUND(AVG(C.PRET_ACHIZITIE), 2) AS PRET_MEDIU_ACHIZITIE
FROM EDITURI E JOIN CARTI C ON E.ID_EDITURA = C.ID_EDITURA GROUP BY E.NUME;

SELECT * FROM VW_EDITURI ORDER BY VALOARE_INVENTAR_ACHIZITIE DESC;

--25.SA SE AFISEZE RESTRICTIILE TABELEI "ZONE";
SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME='ZONE';

COMMIT;

